# Generated by Django 3.0.2 on 2020-03-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('brandOwnerName', models.CharField(max_length=50)),
                ('brandMobileNumber', models.IntegerField()),
                ('brandMainAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.IntegerField()),
                ('productSize', models.CharField(max_length=50)),
                ('productAvailability', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('proudctBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.Brand')),
            ],
        ),
    ]
