# Generated by Django 3.0.2 on 2020-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandMobileNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(max_length=50),
        ),
    ]
